### ISSUE TITLE
Switch away from GPL

### ISSUE THREAD

**Issue by rdrpenguin04** [SNES-Dev/SNES-Dev#4]
If this project is GPL, homebrew starts to have a problem: modifying this workflow in any way means that the resultant modifications need to become public, even if it would be valuable to keep them private (e.g. special linking for unusually-mapped cartridges for piracy resistance). As this project is still relatively new, I would recommend switching to a more permissive license early before it becomes a problem for someone.

**Comment by chorman0773** [comment]
I'll do that immediately

**Comment by rdrpenguin04** [comment]
Make sure to note that the projects that *are* covered under GPL are still GPL
